Busca-de-Alunos2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Busca_de_Alunos2.Models;

namespace Busca_de_Alunos2.Controllers
{
    public class HomeController : Controller
    {
        private BuscaAlunosContext db = new BuscaAlunosContext();

        public ActionResult Index()
        {
            return View(db.Alunos.ToList());
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            string sParam = form["txtPesq"];

            if (!string.IsNullOrWhiteSpace(sParam))
            {
                return View(db.Alunos.Where(x => x.Ra == sParam));
            }
            else
            {
                return View(db.Alunos.ToList());
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Busca-de-Alunos2/Controllers/MapaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Busca_de_Alunos2.Models;

namespace Busca_de_Alunos2.Controllers
{
    public class MapaController : Controller
    {
        private BuscaAlunosContext db = new BuscaAlunosContext();

        public ActionResult Index(int? id)
        {

            if (id == null)
            {
                return View();
            }

            Aluno aluno = db.Alunos.Find(id);

            if (aluno == null)
            {
                return HttpNotFound();
            }

            Pesquisa pesquisa = new Pesquisa();
            pesquisa.Aluno = aluno;
            db.Pesquisas.Add(pesquisa);
            db.SaveChanges();
            
            return View(db.Alunos.Find(id));
           
        }
    }
}

Busca-de-Alunos2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Busca-de-Alunos2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Busca-de-Alunos2/Views/Home/Index.cshtml
@model IEnumerable<Busca_de_Alunos2.Models.Aluno>

@{
    ViewBag.Title = "Home Page";
}

<h5>Pesquisar pelo RA:</h5>
@*<input id="txtPesq" type="text" size="50" placeholder="Digite o RA">
<input type="submit" value="Pesquisar" class="btn btn-default" /> |*@

@using (Html.BeginForm())
{
    @Html.TextBox("txtPesq");
    <input type="submit" value="Pesquisar" class="btn btn-default" />
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.ActionLink("Localização", "Index", "Mapa", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>